### PR TITLE
Check files in folder recursively

### PR DESCRIPTION
**Pull request by louietyj**
As title

**Test Plan**

```
C:\Users\louie\Downloads>dir /b /s /a:-D c:\users\louie\desktop\dummy
c:\users\louie\desktop\dummy\Supergirl.S05E01.HDTV.x264-SVA[rarbg]\RARBG.txt
c:\users\louie\desktop\dummy\Supergirl.S05E01.HDTV.x264-SVA[rarbg]\RARBG_DO_NOT_MIRROR.exe
c:\users\louie\desktop\dummy\Supergirl.S05E01.HDTV.x264-SVA[rarbg]\Supergirl.S05E01.HDTV.x264-SVA.mkv
c:\users\louie\desktop\dummy\Supergirl.S05E01.HDTV.x264-SVA[rarbg]\supergirl.s05e01.hdtv.x264-sva.nfo
```

```
C:\Users\louie\Downloads>OpenSubtitlesDownload.py --cli c:\users\louie\desktop\dummy

>> Title: "Supergirl" Event Horizon
>> Filename: Supergirl.S05E01.HDTV.x264-SVA.mkv
>> Available subtitles:
[92m[1][0m "Supergirl.S05E01.720p.HDTV.x264-AVS.srt"
[92m[2][0m "Supergirl.S05E01.720p.HDTV.x264-AVS-HI.srt" > "HI"
[91m[0][0m Cancel search
>> Enter your choice (0-2):
```

### CODE REVIEW

**Comment by emericg** [comment]
Hi!
Not checking files recursively was actually a feature, because if you launch it on the wrong directory you won't be able to stop the application to go through ALL of your files, at least if your are using the GUI.

Any idea on how to mitigate that?

**Comment by louietyj** [comment]
Hello! I'm on Windows so I'm not too sure what the GUI looks like, but if the concern is with too many files, you could set an explicit warning on the UI? On the shell we can ctrl-C so it's fine.

**Comment by emericg** [comment]
The explicit warning would be already too late, the first process search and dispatch new instances for every file found. So that's why doing this on C: can quickly get out of control ^^

I think the best course of action would be limiting the depth of recursion to like two or three level, but the quickest course of action would probably be to limit recursion to CLI mode (because no new instances are spawned and ctrl-c is possible).

**Comment by emericg** [comment]
Allright I merged this but made it recurse only when using the CLI

**Pull request merged**
